# Header
menu:
  ä¸»é¡µ: /
  æ‰€æœ‰æ–‡ç« : /archives
  éšç¬”: /tags/éšç¬”

# SubNav
subnav:
  github: "https://github.com/HopeLyn"
  #weibo: "#"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:buaa_lyn@163.com"
  #facebook: "#"
  google: "mailto:buaaxigua@gmail.com"
  #twitter: "#"
  linkedin: "https://cn.linkedin.com/in/yannan-li-abb147a3"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# æ˜¯å¦å¼€å¯åŠ¨ç”»æ•ˆæœ
animate: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#ä½ çš„å¤´åƒurl
avatar: https://avatars3.githubusercontent.com/u/8351105?v=3&s=460
#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true
share_addthis: false
#æ˜¯å¦å¼€å¯å¤šè¯´è¯„è®ºï¼Œå¡«å†™ä½ åœ¨å¤šè¯´ç”³è¯·çš„é¡¹ç›®åç§° duoshuo: duoshuo-key
#è‹¥ä½¿ç”¨disqusï¼Œè¯·åœ¨åšå®¢configæ–‡ä»¶ä¸­å¡«å†™disqus_shortnameï¼Œå¹¶å…³é—­å¤šè¯´è¯„è®º
duoshuo: true
#æ˜¯å¦å¼€å¯äº‘æ ‡ç­¾
tagcloud: true

#æ˜¯å¦å¼€å¯å‹æƒ…é“¾æ¥
#ä¸å¼€å¯â€”â€”
#friends: false
#å¼€å¯â€”â€”
friends:
  å¥¥å·´é©¬çš„åšå®¢: http://localhost:4000/
  å¡å¡çš„ç¾ä¸½ä¼ è¯´: http://localhost:4000/
  æœ¬æ³½é©¬çš„åšå®¢: http://localhost:4000/
  å‰æ ¼æ–¯çš„åšå®¢: http://localhost:4000/
  ä¹ å¤§å¤§å¤§ä¸åŒ: http://localhost:4000/
  æ‰˜è’‚çš„åšå®¢: http://localhost:4000/

#æ˜¯å¦å¼€å¯â€œå…³äºæˆ‘â€ã€‚
#ä¸å¼€å¯â€”â€”
#aboutme: false
#å¼€å¯â€”â€”
aboutme: å–œæ¬¢ç¼–ç¨‹ï¼Œçƒ­çˆ±ç”Ÿæ´»çš„ğŸ‰å›
